name: watering_app 

description: A garden moisture checking app without weather. 

 

version: 1.0.0+1 

 

environment: 

  sdk: ">=2.17.0 <3.0.0" 

 
 
dependencies: 

  flutter: 

    sdk: flutter 

  fl_chart: ^0.63.0 

 

dev_dependencies: 

  flutter_test: 

    sdk: flutter 

 

flutter: 

  uses-material-design: true